from PyQt5 import QtCore, QtGui, QtWidgets

class WordDialog(QtWidgets.QDialog):
  def __init__(self ,parent):
    super(WordDialog,self).__init__(parent)
    vLayout     = QtWidgets.QVBoxLayout(self)
    hLowLayout  = QtWidgets.QHBoxLayout()
    okButton    = QtWidgets.QPushButton(self)
    okButton.setText("OK")
    okButton.clicked.connect(self.accept)
    cancelButton = QtWidgets.QPushButton(self)
    cancelButton.setText("Cancel")
    cancelButton.clicked.connect(self.reject)
    hHighLayout = QtWidgets.QHBoxLayout()
    hLowLayout.addWidget(okButton)
    hLowLayout.addWidget(cancelButton)
    vLayout.addLayout(hHighLayout)
    vLayout.addLayout(hLowLayout)
    vLeftLayout = QtWidgets.QVBoxLayout()
    vRightLayout = QtWidgets.QVBoxLayout()
    hHighLayout.addLayout(vLeftLayout)
    hHighLayout.addLayout(vRightLayout)
    textLabel = QtWidgets.QLabel(self)
    textLabel.setText("Please enter a new word")
    textLabel.setMaximumSize(QtCore.QSize(300, 50))
    lineEdit = QtWidgets.QLineEdit(self)
    lineEdit.setMaximumSize(QtCore.QSize(400, 50))
    vLeftLayout.addWidget(textLabel)
    vLeftLayout.addWidget(lineEdit)
